// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Wizard struct {
	ID    pgtype.UUID
	Name  string
	Level int32
	Bio   string
}
