services:
  wizardapi:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile.wizardapi
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: 
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile.goose
    environment:
      GOOSE_DBSTRING: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      GOOSE_DRIVER: postgres
    volumes:
      - ../../migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5