FROM golang:1.25 AS builder

WORKDIR /builder
COPY . .
RUN go mod download
RUN go build -o wizardapi ./cmd/wizardapi

FROM gcr.io/distroless/base AS runner

WORKDIR /runner
COPY --from=builder /builder/wizardapi .

EXPOSE 8080

ENTRYPOINT ["./wizardapi"]